const RARITY = {
  COMMON: 'Common',
  UNCOMMON: 'Uncommon',
  RARE: 'Rare',
  EPIC: 'Epic',
  LEGENDARY: 'Legendary',
  MYTHIC: 'Mythic'
};

const RARITY_ORDER = [
  RARITY.COMMON, RARITY.UNCOMMON, RARITY.RARE,
  RARITY.EPIC, RARITY.LEGENDARY, RARITY.MYTHIC
];

const SLOTS = {
  MAIN_HAND: 'main-hand', OFF_HAND: 'off-hand',
  HELMET: 'helmet', ARMOR: 'armor', LEGS: 'legs',
  ACCESSORY_1: 'accessory-1', ACCESSORY_2: 'accessory-2', ACCESSORY_3: 'accessory-3'
};

const RARITY_MULTIPLIERS = {
  [RARITY.COMMON]: 1.0,
  [RARITY.UNCOMMON]: 1.94,
  [RARITY.RARE]: 2.94,
  [RARITY.EPIC]: 4.0,
  [RARITY.LEGENDARY]: 6.25,
  [RARITY.MYTHIC]: 8.75
};

const TEMPER_BONUS = [0, 1, 2, 3, 5, 7, 9, 12, 15, 18, 22, 26, 30, 34, 38, 42];
const TEMPER_MAX_TIER = 15;

const SETS = {
  NONE: 'no-set'
};

const SET_LIST = [
  { id: 'arctic-flipper', name: 'Arctic Flipper', icon: 'icons/sets/arctic-flipper.webp', iconStyle: 'banner' },
  { id: 'blackwing', name: 'Blackwing', icon: 'icons/sets/blackwing.webp', iconStyle: 'banner' },
  { id: 'bon-appeti', name: 'Bon Appeti', icon: 'icons/sets/bon-appeti.webp', iconStyle: 'banner' },
  { id: 'champion', name: 'Champion', icon: 'icons/sets/champion.webp', iconStyle: 'banner' },
  { id: 'cottageroar', name: 'Cottageroar', icon: 'icons/sets/cottageroar.webp', iconStyle: 'banner' },
  { id: 'emperor', name: 'Emperor', icon: 'icons/sets/emperor.webp', iconStyle: 'icon' },
  { id: 'exalted', name: 'Exalted', icon: null, iconStyle: null },
  { id: 'frostwing', name: 'Frostwing', icon: 'icons/sets/frostwing.webp', iconStyle: 'banner' },
  { id: 'gargantua', name: 'Gargantua', icon: 'icons/sets/gargantua.webp', iconStyle: 'banner' },
  { id: 'gawrilla', name: 'Gawrilla', icon: 'icons/sets/gawrilla.webp', iconStyle: 'banner' },
  { id: 'grim-reaper', name: 'Grim Reaper', icon: 'icons/sets/grim-reaper.webp', iconStyle: 'banner' },
  { id: 'gryphon', name: 'Gryphon', icon: 'icons/sets/gryphon.webp', iconStyle: 'banner' },
  { id: 'hardrox', name: 'Hardrox', icon: 'icons/sets/hardrox.webp', iconStyle: 'banner' },
  { id: 'hell-drider', name: 'Hell Drider', icon: 'icons/sets/hell-drider.webp', iconStyle: 'banner' },
  { id: 'hootclaw', name: 'Hootclaw', icon: 'icons/sets/hootclaw.webp', iconStyle: 'banner' },
  { id: 'hunter', name: 'Hunter', icon: 'icons/sets/hunter.webp', iconStyle: 'banner' },
  { id: 'jade-wyrm', name: 'Jade Wyrm', icon: 'icons/sets/jade-wyrm.webp', iconStyle: 'banner' },
  { id: 'kung-fu-panda', name: 'Kung Fu Panda', icon: 'icons/sets/kung-fu-panda.webp', iconStyle: 'icon' },
  { id: 'mecha-trojan', name: 'Mecha Trojan', icon: 'icons/sets/mecha-trojan.webp', iconStyle: 'banner' },
  { id: 'mega-maggot', name: 'Mega Maggot', icon: 'icons/sets/mega-maggot.webp', iconStyle: 'banner' },
  { id: 'necrosis', name: 'Necrosis', icon: 'icons/sets/necrosis.webp', iconStyle: 'banner' },
  { id: 'night-fury', name: 'Night Fury', icon: null, iconStyle: null },
  { id: 'noceros', name: 'Noceros', icon: 'icons/sets/noceros.webp', iconStyle: 'banner' },
  { id: 'queen-bee', name: 'Queen Bee', icon: 'icons/sets/queen-bee.webp', iconStyle: 'banner' },
  { id: 'saberfang', name: 'Saberfang', icon: 'icons/sets/saberfang.webp', iconStyle: 'banner' },
  { id: 'sacred', name: 'Sacred', icon: 'icons/sets/sacred.webp', iconStyle: 'icon' },
  { id: 'sagittarius', name: 'Sagittarius', icon: 'icons/sets/sagittarius.webp', iconStyle: 'icon' },
  { id: 'serpent-gladiator', name: 'Serpent Gladiator', icon: 'icons/sets/serpent-gladiator.webp', iconStyle: 'banner' },
  { id: 'snow-beast', name: 'Snow Beast', icon: 'icons/sets/snow-beast.webp', iconStyle: 'banner' },
  { id: 'steampath', name: 'Steampath', icon: 'icons/sets/steampath.webp', iconStyle: 'banner' },
  { id: 'terrorthorn', name: 'Terrorthorn', icon: 'icons/sets/terrorthorn.webp', iconStyle: 'banner' },
  { id: 'tidal-titan', name: 'Tidal Titan', icon: 'icons/sets/tidal-titan.webp', iconStyle: 'banner' },
  { id: 'voodoo-shaman', name: 'Voodoo Shaman', icon: 'icons/sets/voodoo-shaman.webp', iconStyle: 'banner' },
  { id: 'no-set', name: 'No Set', icon: null, iconStyle: null },
];

const ITEMS = {
  [SLOTS.MAIN_HAND]: [
    { name: "Dragon's Bite", level: 40, set: 'blackwing', icon: 'icons/items/Dragons_Bite.webp', stats: { infantryAttack: 1.5, armyHp: 1.5 } },
    { name: "Decadent Sword", level: 55, set: 'bon-appeti', icon: 'icons/items/Decadent_Sword.png', stats: { infantryAttack: 4.0, rangedAttack: 4.0, rangedDefense: 1.5, infantryHp: 1.5 } },
    { name: "Champion Blade", level: 60, set: 'champion', icon: 'icons/items/Champion_Blade.png', stats: { infantryAttack: 3.2, rangedAttack: 3.2, armyAttack: 2.4, armyDefense: 2.75, researchSpeed: 2.4 } },
    { name: "Champion Edge", level: 60, set: 'champion', icon: 'icons/items/Champion_Edge.png', stats: { cavalryAttack: 5.5, armyAttack: 2.4, armyDefense: 2.75, researchSpeed: 2.4 } },
    { name: "Champion Greatsword", level: 60, set: 'champion', icon: 'icons/items/Champion_Greatsword.png', stats: { cavalryAttack: 3.2, rangedAttack: 3.2, armyAttack: 2.4, armyDefense: 2.75, researchSpeed: 2.4 } },
    { name: "Kingslayer", level: 60, set: 'emperor', icon: 'icons/items/Kingslayer.webp', fixedGrade: 'Mythic', stats: { armyAttack: 45.0, armyDefense: 25.0, armyHp: 15.0 } },
    { name: "NewItem14", level: 60, set: 'exalted', icon: 'icons/items/NewItem14.webp', fixedGrade: 'Mythic', stats: { armyAttack: 40.0, armyDefense: 20.0, armyHp: 10.0 } },
    { name: "Frostwing Greatsword", level: 60, set: 'frostwing', icon: 'icons/items/Frostwing_Greatsword.png', stats: { infantryAttack: 3.0, cavalryAttack: 3.0, rangedAttack: 2.0 } },
    { name: "Horn Cudgel", level: 60, set: 'gargantua', icon: 'icons/items/Horn_Cudgel.webp', stats: { cavalryAttack: 4.8, cavalryDefense: 2.4, trapDefense: 5.5 } },
    { name: "Eon Axe", level: 60, set: 'gawrilla', icon: 'icons/items/Eon_Axe.webp', stats: { cavalryAttack: 6.0, cavalryHp: 1.6, cavalryDefense: 1.6 } },
    { name: "Harbinger", level: 40, set: 'grim-reaper', icon: 'icons/items/Harbinger.png', stats: { rangedAttack: 1.2, armyDefense: 1.5 } },
    { name: "Skull Crusher", level: 60, set: 'hell-drider', icon: 'icons/items/Skull_Crusher.png', stats: { rangedAttack: 2.4, infantryDefense: 4.0, armyAttack: 3.2 } },
    { name: "Wyrm Rod", level: 50, set: 'jade-wyrm', icon: 'icons/items/Wyrm_Rod.webp', stats: { rangedAttack: 4.0, rangedHp: 2.8, timberProduction: 8.0 } },
    { name: "Yin Yang Staff", level: 60, set: 'kung-fu-panda', icon: 'icons/items/Yin_Yang_Staff.webp', fixedGrade: 'Legendary', stats: { armyAttack: 3.0, armyDefense: 3.0, armyHp: 3.0 } },
    { name: "Malicious Saw", level: 50, set: 'mecha-trojan', icon: 'icons/items/Malicious_Saw.png', stats: { infantryAttack: 4.0, siegeAttack: 4.0, infantryDefense: 2.4 } },
    { name: "Collab Item04", level: 60, set: 'night-fury', icon: 'icons/items/Collab_Item04.webp', fixedGrade: 'Legendary', stats: { travelSpeed: 5.0 } },
    { name: "Falcon Gale", level: 40, set: 'no-set', icon: 'icons/items/Falcon_Gale.png', stats: { cavalryAttack: 1.6, rangedAttack: 0.8, trapAttack: 0.8 } },
    { name: "Fatal Flail", level: 21, set: 'no-set', icon: 'icons/items/Fatal_Flail.webp', stats: { infantryAttack: 0.88, trapAttack: 0.48 } },
    { name: "Fiery Tomahawk", level: 40, set: 'no-set', icon: 'icons/items/Fiery_Tomahawk.webp', stats: { cavalryAttack: 1.6, infantryAttack: 1.04, rangedAttack: 0.56 } },
    { name: "Lumos Lance", level: 27, set: 'no-set', icon: 'icons/items/Lumos_Lance.webp', stats: { constructionSpeed: 0.88, infantryAttack: 1.04, rangedAttack: 0.56 } },
    { name: "Reaper's Axe", level: 1, set: 'no-set', icon: 'icons/items/Reapers_Axe.webp', stats: { cavalryAttack: 0.24, infantryAttack: 0.24 } },
    { name: "Septic Spikes", level: 35, set: 'no-set', icon: 'icons/items/Septic_Spikes.webp', stats: { cavalryAttack: 1.44, infantryAttack: 1.44, siegeAttack: 1.04 } },
    { name: "Shadow Steel", level: 15, set: 'no-set', icon: 'icons/items/Shadow_Steel.webp', stats: { cavalryAttack: 0.56, rangedAttack: 0.32, siegeAttack: 0.4 } },
    { name: "Slayer's Sword", level: 15, set: 'no-set', icon: 'icons/items/Slayers_Sword.webp', stats: { constructionSpeed: 0.48, infantryAttack: 0.48 } },
    { name: "Tempest Crossbow", level: 31, set: 'no-set', icon: 'icons/items/Tempest_Crossbow.webp', stats: { infantryAttack: 1.28, rangedAttack: 0.48, siegeAttack: 0.56 } },
    { name: "Trident", level: 35, set: 'no-set', icon: 'icons/items/Trident.webp', stats: { constructionSpeed: 1.12, siegeAttack: 1.04, trapAttack: 0.8 } },
    { name: "Venom Stinger", level: 40, set: 'no-set', icon: 'icons/items/Venom_Stinger.webp', stats: { infantryAttack: 1.6, rangedAttack: 0.8, trapAttack: 0.8 } },
    { name: "Wrath Star", level: 31, set: 'no-set', icon: 'icons/items/Wrath_Star.webp', stats: { cavalryAttack: 1.28, rangedAttack: 0.64 } },
    { name: "Electric Lance", level: 50, set: 'noceros', icon: 'icons/items/Electric_Lance.webp', stats: { travelSpeed: 2.4, researchSpeed: 1.5, gatheringSpeed: 4.8 } },
    { name: "Nectar Orb", level: 55, set: 'queen-bee', icon: 'icons/items/Nectar_Orb.webp', stats: { cavalryAttack: 4.0, rangedAttack: 4.0, cavalryDefense: 1.5, rangedHp: 1.5 } },
    { name: "Ripper Claw", level: 45, set: 'saberfang', icon: 'icons/items/Ripper_Claw.webp', stats: { cavalryAttack: 3.2, cavalryDefense: 3.2, travelSpeed: 2.4 } },
    { name: "Sacred Broadsword", level: 60, set: 'sacred', icon: 'icons/items/Sacred_Broadsword.webp', fixedGrade: 'Legendary', stats: { constructionSpeed: 10.0, infantryAttack: 5.0, rangedAttack: 5.0, cavalryAttack: 5.0 } },
    { name: "Sagittarius Bow", level: 60, set: 'sagittarius', icon: 'icons/items/Sagittarius_Bow.webp', fixedGrade: 'Legendary', stats: { travelSpeed: 5.0 } },
    { name: "Steam Pistol", level: 55, set: 'steampath', icon: 'icons/items/Steam_Pistol.webp', stats: { craftingSpeed: 2.2, cavalryDefense: 1.6, craftingCapacity: 34.0 } },
    { name: "Ghastly Cane", level: 60, set: 'cottageroar', icon: 'icons/sets/Ghastly_Cane.webp', stats: { infantryAttack: 5.2, infantryHp: 1.6, armyDefense: 2.4 } },
    { name: "Terror Lash", level: 55, set: 'terrorthorn', icon: 'icons/items/Terror_Lash.webp', stats: { infantryAttack: 4.5, infantryDefense: 1.5, constructionSpeed: 1.5 } },
    { name: "Kraken's Anchor", level: 55, set: 'tidal-titan', icon: 'icons/items/Krakens_Anchor.webp', stats: { infantryAttack: 4.0, cavalryAttack: 4.0, infantryDefense: 2.05, cavalryHp: 2.05 } },
    { name: "Earthshatter", level: 60, set: 'hunter', icon: 'icons/items/Earthshatter.png', stats: { maxEnergy: 320.0, monsterHuntDmg: 4.5 } },
    { name: "Bone Staff", level: 60, set: 'voodoo-shaman', icon: 'icons/items/Bone_Staff.png', stats: { mergingSpeed: 2.4, familiarTrainingExp: 8.0, familiarSkillExp: 0.5 } },
  ],
  [SLOTS.OFF_HAND]: [
    { name: "Arctic Net", level: 45, set: 'arctic-flipper', icon: 'icons/items/Arctic_Net.webp', stats: { cavalryAttack: 1.6, rangedAttack: 1.6, cavalryDefense: 0.8, rangedHp: 0.8 } },
    { name: "Dragon's Fist", level: 50, set: 'blackwing', icon: 'icons/items/Dragons_Fist.webp', stats: { cavalryAttack: 3.5, armyHp: 3.2 } },
    { name: "Champion Katar", level: 60, set: 'champion', icon: 'icons/items/Champion_Katar.webp', stats: { cavalryAttack: 5.5, rangedAttack: 4.8, armyDefense: 3.2, trainingSpeed: 1.5 } },
    { name: "Champion Lamp", level: 60, set: 'champion', icon: 'icons/items/Champion_Lamp.webp', stats: { infantryAttack: 4.8, rangedAttack: 5.5, armyDefense: 3.2, trainingSpeed: 1.5 } },
    { name: "Champion Light", level: 60, set: 'champion', icon: 'icons/items/Champion_Light.webp', stats: { infantryAttack: 5.5, cavalryAttack: 4.8, armyDefense: 3.2, trainingSpeed: 1.5 } },
    { name: "Imperial Bulwark", level: 60, set: 'emperor', icon: 'icons/items/Imperial_Bulwark.webp', fixedGrade: 'Mythic', stats: { armyAttack: 35.0, armyDefense: 31.0, armyHp: 30.0 } },
    { name: "NewItem15", level: 60, set: 'exalted', icon: 'icons/items/NewItem15.webp', fixedGrade: 'Mythic', stats: { armyAttack: 30.0, armyDefense: 25.0, armyHp: 25.0 } },
    { name: "Frostwing Shield", level: 40, set: 'frostwing', icon: 'icons/items/Frostwing_Shield.webp', stats: { armyDefense: 2.0, armyHp: 1.35, wallDefense: 1.45 } },
    { name: "Eternal Codex", level: 60, set: 'grim-reaper', icon: 'icons/items/Eternal_Codex.webp', stats: { cavalryAttack: 3.2, rangedAttack: 5.5, cavalryHp: 3.2 } },
    { name: "Gryphon's Talon", level: 45, set: 'gryphon', icon: 'icons/items/Gryphons_Talon.png', stats: { goldProduction: 5.6, constructionSpeed: 2.8 } },
    { name: "Dark Aegis", level: 50, set: 'hell-drider', icon: 'icons/items/Dark_Aegis.webp', stats: { infantryAttack: 1.5, armyAttack: 1.5 } },
    { name: "Lunar Boomerang", level: 60, set: 'hootclaw', icon: 'icons/items/Lunar_Boomerang.webp', stats: { cavalryAttack: 4.8, cavalryDefense: 2.4, cavalryHp: 2.4 } },
    { name: "Wyrm Lantern", level: 40, set: 'jade-wyrm', icon: 'icons/items/Wyrm_Lantern.webp', stats: { rangedAttack: 1.5, cavalryDefense: 8.8, rangedHp: 1.45 } },
    { name: "Viral Switchblade", level: 50, set: 'mecha-trojan', icon: 'icons/items/Viral_Switchblade.webp', stats: { infantryAttack: 2.4, rangedAttack: 2.4, siegeAttack: 4.0 } },
    { name: "Orb of Pestilence", level: 45, set: 'mega-maggot', icon: 'icons/items/Orb_of_Pestilence.webp', stats: { cavalryAttack: 1.75, trapAttack: 4.8 } },
    { name: "Spirit Axe", level: 60, set: 'necrosis', icon: 'icons/items/Spirit_Axe.webp', stats: { infantryAttack: 4.0, cavalryAttack: 4.0, cavalryHp: 1.6, armyDefense: 1.6 } },
    { name: "Collab Item05", level: 60, set: 'night-fury', icon: 'icons/items/Collab_Item05.webp', fixedGrade: 'Legendary', stats: { constructionSpeed: 5.0 } },
    { name: "Crusader's Shield", level: 40, set: 'no-set', icon: 'icons/items/Crusaders_Shield.webp', stats: { infantryAttack: 0.72, rangedAttack: 1.04, siegeAttack: 1.6 } },
    { name: "Fiendish Fang", level: 7, set: 'no-set', icon: 'icons/items/Fiendish_Fang.webp', stats: { cavalryAttack: 0.24, trapAttack: 0.56 } },
    { name: "Herald's Crest", level: 19, set: 'no-set', icon: 'icons/items/Heralds_Crest.webp', stats: { cavalryAttack: 0.4, trapAttack: 0.32, armyHp: 1.04 } },
    { name: "Lunar Scimitar", level: 35, set: 'no-set', icon: 'icons/items/Lunar_Scimitar.webp', stats: { rangedAttack: 1.44, siegeAttack: 2.24, armyHp: 1.84 } },
    { name: "Morning Star", level: 25, set: 'no-set', icon: 'icons/items/Morning_Star.webp', stats: { infantryAttack: 0.48, rangedAttack: 1.04 } },
    { name: "Noah's Cube", level: 35, set: 'no-set', icon: 'icons/items/Noahs_Cube.webp', stats: { cavalryAttack: 0.8, rangedAttack: 0.96, siegeAttack: 2.24 } },
    { name: "Rabid Claws", level: 31, set: 'no-set', icon: 'icons/items/Rabid_Claws.webp', stats: { cavalryAttack: 0.64, infantryAttack: 0.56, siegeAttack: 1.84 } },
    { name: "Tome of Saints", level: 13, set: 'no-set', icon: 'icons/items/Tome_of_Saints.webp', stats: { researchSpeed: 0.32, rangedAttack: 0.48 } },
    { name: "Umbral Whisper", level: 31, set: 'no-set', icon: 'icons/items/Umbral_Whisper.webp', stats: { trapAttack: 0.56, armyHp: 1.6 } },
    { name: "Vice Grips", level: 40, set: 'no-set', icon: 'icons/items/Vice_Grips.webp', stats: { researchSpeed: 0.8, trapAttack: 0.72, armyHp: 2.08 } },
    { name: "Sacred Gauntlets", level: 60, set: 'sacred', icon: 'icons/items/Sacred_Gauntlets.webp', fixedGrade: 'Legendary', stats: { researchSpeed: 5.0 } },
    { name: "Sacred Staff", level: 60, set: 'sacred', icon: 'icons/items/Sacred_Staff.webp', fixedGrade: 'Legendary', stats: { constructionSpeed: 10.0, armyHp: 5.0, armyDefense: 5.0 } },
    { name: "Sagittarius Gauntlet", level: 60, set: 'sagittarius', icon: 'icons/items/Sagittarius_Gauntlet.webp', fixedGrade: 'Legendary', stats: { constructionSpeed: 5.0 } },
    { name: "Venom Blade", level: 60, set: 'serpent-gladiator', icon: 'icons/items/Venom_Blade.webp', stats: { infantryAttack: 4.0, rangedAttack: 4.0, rangedDefense: 1.6, armyHp: 1.6 } },
    { name: "Winter Mitts", level: 50, set: 'snow-beast', icon: 'icons/items/Winter_Mitts.webp', stats: { rangedAttack: 1.6, infantryDefense: 5.2, armyDefense: 4.0, armyHp: 4.0 } },
    { name: "Mechanical Gauntlet", level: 60, set: 'steampath', icon: 'icons/items/Mechanical_Gauntlet.webp', stats: { craftingSpeed: 2.2, infantryDefense: 1.6, craftingCapacity: 45.0 } },
    { name: "Eerie Lantern", level: 60, set: 'cottageroar', icon: 'icons/sets/Eerie_Lantern.webp', stats: { infantryAttack: 4.8, infantryDefense: 1.6, armyHp: 1.6 } },
    { name: "Terror Blade", level: 40, set: 'terrorthorn', icon: 'icons/items/Terror_Blade.webp', stats: { infantryAttack: 1.45, infantryHp: 1.95, timberProduction: 4.0 } },
    { name: "Call of the Deep", level: 60, set: 'tidal-titan', icon: 'icons/items/Call_of_the_Deep.webp', stats: { infantryAttack: 2.4, cavalryAttack: 2.4, infantryHp: 1.5, cavalryHp: 1.5 } },
    { name: "Hunting Mace", level: 50, set: 'hunter', icon: 'icons/items/Hunting_Mace.png', stats: { monsterHuntDmg: 4.0 } },
    { name: "Blighted Vial", level: 55, set: 'voodoo-shaman', icon: 'icons/items/Blighted_Vial.png', stats: { familiarTrainingExp: 8.0, mergingSpeedSkillstone: 1.5 } },
  ],
  [SLOTS.HELMET]: [
    { name: "Orca Mask", level: 50, set: 'arctic-flipper', icon: 'icons/items/Orca_Mask.webp', stats: { cavalryAttack: 2.1, rangedAttack: 2.1, rangedDefense: 1.1, cavalryHp: 1.3 } },
    { name: "Indulgent Visage", level: 40, set: 'bon-appeti', icon: 'icons/items/Indulgent_Visage.webp', stats: { infantryAttack: 1.5, rangedAttack: 1.5 } },
    { name: "Champion Armet", level: 60, set: 'champion', icon: 'icons/items/Champion_Armet.webp', stats: { cavalryAttack: 4.0, rangedAttack: 4.0, armyAttack: 1.5, armyHp: 3.2, goldProduction: 12.0 } },
    { name: "Champion Helm", level: 60, set: 'champion', icon: 'icons/items/Champion_Helm.webp', stats: { cavalryAttack: 4.8, armyAttack: 1.5, armyHp: 5.5, goldProduction: 12.0 } },
    { name: "Champion Visor", level: 60, set: 'champion', icon: 'icons/items/Champion_Visor.webp', stats: { infantryAttack: 4.0, rangedAttack: 4.0, armyAttack: 1.5, armyHp: 3.2, goldProduction: 12.0 } },
    { name: "Noble Helm", level: 60, set: 'emperor', icon: 'icons/items/Noble_Helm.webp', fixedGrade: 'Mythic', stats: { armyAttack: 40.0, armyDefense: 10.0, armyHp: 40.0 } },
    { name: "Sovereign's Helm", level: 60, set: 'exalted', icon: 'icons/items/Sovereigns_Helm.webp', fixedGrade: 'Mythic', stats: { armyAttack: 35.0, armyDefense: 5.0, armyHp: 35.0 } },
    { name: "Frostwing Helm", level: 50, set: 'frostwing', icon: 'icons/items/Frostwing_Helm.webp', stats: { rangedAttack: 1.45, siegeAttack: 1.2, armyHp: 1.85 } },
    { name: "Blood-Stained Helm", level: 40, set: 'gargantua', icon: 'icons/items/Blood-Stained_Helm.webp', stats: { cavalryAttack: 1.2, cavalryDefense: 1.2, cavalryHp: 1.2 } },
    { name: "Ancient Hat", level: 55, set: 'grim-reaper', icon: 'icons/items/Ancient_Hat.webp', stats: { rangedAttack: 4.5, rangedDefense: 4.0, armyDefense: 2.4 } },
    { name: "Coarse Helm", level: 40, set: 'hardrox', icon: 'icons/items/Coarse_Helm.png', stats: { trainingSpeed: 0.8, forgingSpeed: 2.4, timberProduction: 4.0 } },
    { name: "Night Goggles", level: 40, set: 'steampath', icon: null, stats: { craftingSpeed: 1.1, craftingCapacity: 11.0, timberProduction: 1.6 } },
    { name: "Strigine Hood", level: 45, set: 'hootclaw', icon: 'icons/items/Strigine_Hood.webp', stats: { cavalryAttack: 1.1, cavalryHp: 1.6, armyHp: 0.5 } },
    { name: "Wyrmbone Coronet", level: 60, set: 'jade-wyrm', icon: 'icons/items/Wyrmbone_Coronet.webp', stats: { rangedAttack: 5.25, rangedDefense: 3.25, armyHp: 2.0, researchSpeed: 1.5 } },
    { name: "Warriors Hat", level: 60, set: 'kung-fu-panda', icon: 'icons/items/Warriors_Hat.webp', fixedGrade: 'Legendary', stats: { rangedAttack: 5.0, rangedDefense: 5.0, rangedHp: 5.0 } },
    { name: "Shadow Helm", level: 50, set: 'mega-maggot', icon: 'icons/items/Shadow_Helm.webp', stats: { infantryAttack: 1.5, trapAttack: 4.8, trapDefense: 4.8, wallDefense: 2.4 } },
    { name: "Devourer Helm", level: 50, set: 'necrosis', icon: 'icons/items/Devourer_Helm.webp', stats: { infantryAttack: 2.1, cavalryAttack: 2.1, cavalryDefense: 1.6, infantryHp: 0.8 } },
    { name: "Collab Item01", level: 60, set: 'night-fury', icon: 'icons/items/Collab_Item01.webp', fixedGrade: 'Legendary', stats: { travelSpeed: 5.0 } },
    { name: "Barbarian Helmet", level: 17, set: 'no-set', icon: 'icons/items/Barbarian_Helmet.webp', stats: { infantryAttack: 0.4, armyDefense: 0.72, wallDefense: 0.88 } },
    { name: "Berserker Tuskhelm", level: 40, set: 'no-set', icon: 'icons/items/Berserker_Tuskhelm.webp', stats: { infantryAttack: 0.8, trapAttack: 1.6, armyDefense: 1.68 } },
    { name: "Deathgazer", level: 40, set: 'no-set', icon: 'icons/items/Deathgazer.webp', stats: { trapAttack: 1.6, armyDefense: 2.56, wallDefense: 1.84 } },
    { name: "Devil Visage", level: 35, set: 'no-set', icon: 'icons/items/Devil_Visage.webp', stats: { armyDefense: 2.32, wallDefense: 1.68 } },
    { name: "Helmet of Conquest", level: 35, set: 'no-set', icon: 'icons/items/Helmet_of_Conquest.webp', stats: { goldProduction: 4.24, infantryAttack: 0.8, trapAttack: 1.44 } },
    { name: "Prosecutor's Will", level: 23, set: 'no-set', icon: 'icons/items/Prosecutors_Will.webp', stats: { infantryAttack: 0.48, trapAttack: 0.96 } },
    { name: "Skull King's Legacy", level: 5, set: 'no-set', icon: 'icons/items/Skull_Kings_Legacy.webp', stats: { infantryAttack: 0.16, trapAttack: 0.32 } },
    { name: "Wanderer's Hood", level: 29, set: 'no-set', icon: 'icons/items/Wanderers_Hood.webp', stats: { foodProduction: 5.12, trapAttack: 1.2, armyDefense: 2.0 } },
    { name: "Chieftain Headdress", level: 11, set: 'no-set', icon: 'icons/items/Chieftain_Headdress.webp', stats: { foodProduction: 2.08 } },
    { name: "Gladiator Helm", level: 29, set: 'no-set', icon: 'icons/items/Gladiator_Helm.webp', stats: { wallDefense: 1.44 } },
    { name: "Noceros Mask", level: 40, set: 'noceros', icon: 'icons/items/Noceros_Mask.png', stats: { travelSpeed: 2.4, constructionSpeed: 1.5, gatheringSpeed: 2.4 } },
    { name: "Bumblehelm", level: 60, set: 'queen-bee', icon: 'icons/items/Bumblehelm.webp', stats: { cavalryAttack: 4.8, rangedAttack: 4.8, armyHp: 3.2 } },
    { name: "Beast Helm", level: 60, set: 'saberfang', icon: 'icons/items/Beast_Helm.webp', stats: { infantryAttack: 4.8, cavalryAttack: 4.0, armyHp: 2.4, travelSpeed: 5.5 } },
    { name: "Sacred Helm", level: 60, set: 'sacred', icon: 'icons/items/Sacred_Helm.webp', fixedGrade: 'Legendary', stats: { goldProduction: 13.0 } },
    { name: "Sagittarius Helmet", level: 60, set: 'sagittarius', icon: 'icons/items/Sagittarius_Helmet.webp', fixedGrade: 'Legendary', stats: { travelSpeed: 5.0 } },
    { name: "Serpent Helm", level: 60, set: 'serpent-gladiator', icon: 'icons/items/Serpent_Helm.webp', stats: { infantryAttack: 4.8, rangedAttack: 4.8, infantryHp: 2.4, armyDefense: 4.0 } },
    { name: "Hunting Helm", level: 60, set: 'hunter', icon: 'icons/items/Hunting_Helm.png', stats: { energySaver: 0.8, maxEnergy: 450.0, monsterHuntDmg: 1.5 } },
    { name: "Accursed Mask", level: 50, set: 'voodoo-shaman', icon: 'icons/items/Accursed_Mask.png', stats: { mergingSpeed: 4.8, mergingSpeedSkillstone: 0.5 } },
  ],
  [SLOTS.ARMOR]: [
    { name: "Hedonic Cuirass", level: 55, set: 'bon-appeti', icon: 'icons/items/Hedonic_Cuirass.webp', stats: { infantryAttack: 4.0, rangedAttack: 4.0, infantryHp: 1.8 } },
    { name: "Champion Cuirass", level: 60, set: 'champion', icon: 'icons/items/Champion_Cuirass.webp', stats: { cavalryAttack: 4.8, armyAttack: 1.5, armyDefense: 5.5, armyHp: 2.4, upkeepReduction: 8.25 } },
    { name: "Champion Mail", level: 60, set: 'champion', icon: 'icons/items/Champion_Mail.webp', stats: { infantryAttack: 4.8, armyAttack: 1.5, armyDefense: 5.5, armyHp: 2.4, upkeepReduction: 8.25 } },
    { name: "Champion Plate", level: 60, set: 'champion', icon: 'icons/items/Champion_Plate.webp', stats: { rangedAttack: 5.5, armyDefense: 6.8, upkeepReduction: 8.25, armyHp: 4.0 } },
    { name: "Regal Robes", level: 60, set: 'emperor', icon: 'icons/items/Regal_Robes.webp', fixedGrade: 'Mythic', stats: { armyAttack: 35.0, armyDefense: 50.0, armyHp: 25.0, upkeepReduction: 52.0 } },
    { name: "NewItem12", level: 60, set: 'exalted', icon: 'icons/items/NewItem12.webp', fixedGrade: 'Mythic', stats: { armyAttack: 30.0, armyDefense: 45.0, armyHp: 20.0, upkeepReduction: 52.0 } },
    { name: "Frostwing Armor", level: 50, set: 'frostwing', icon: 'icons/items/Frostwing_Armor.png', stats: { infantryAttack: 1.2, rangedAttack: 1.2, siegeAttack: 2.0 } },
    { name: "Brass Armor", level: 45, set: 'gawrilla', icon: 'icons/items/Brass_Armor.webp', stats: { cavalryAttack: 1.45, cavalryHp: 1.75, cavalryDefense: 1.1 } },
    { name: "Deathly Mantle", level: 50, set: 'grim-reaper', icon: 'icons/items/Deathly_Mantle.webp', stats: { rangedAttack: 3.2, trapAttack: 2.4, armyDefense: 2.4 } },
    { name: "Armor of the Abyss", level: 40, set: 'hell-drider', icon: 'icons/items/Armor_of_the_Abyss.webp', stats: { infantryDefense: 0.8, cavalryHp: 0.8, armyAttack: 0.8 } },
    { name: "Beastly Breastplate", level: 60, set: 'hootclaw', icon: 'icons/items/Beastly_Breastplate.webp', stats: { rangedAttack: 5.6, rangedHp: 2.4, armyDefense: 3.2 } },
    { name: "Dragon Coat", level: 60, set: 'kung-fu-panda', icon: 'icons/items/Dragon_Coat.webp', fixedGrade: 'Legendary', stats: { infantryAttack: 5.0, infantryDefense: 5.0, infantryHp: 5.0 } },
    { name: "Firewall Plate", level: 60, set: 'mecha-trojan', icon: 'icons/items/Firewall_Plate.png', stats: { infantryAttack: 3.2, cavalryAttack: 4.8, siegeAttack: 4.8, armyHp: 2.4 } },
    { name: "Grimy Plate", level: 40, set: 'mega-maggot', icon: 'icons/items/Grimy_Plate.webp', stats: { infantryAttack: 1.2, infantryHp: 1.45, wallDefense: 1.5 } },
    { name: "Skeletal Armor", level: 45, set: 'necrosis', icon: 'icons/items/Skeletal_Armor.webp', stats: { infantryAttack: 1.6, cavalryAttack: 1.6, infantryDefense: 1.1, cavalryHp: 0.95 } },
    { name: "Cavalry Mail", level: 35, set: 'no-set', icon: 'icons/items/Cavalry_Mail.webp', stats: { researchSpeed: 1.12, foodProduction: 4.96, siegeAttack: 1.12 } },
    { name: "Centaur Saddle", level: 35, set: 'no-set', icon: 'icons/items/Centaur_Saddle.webp', stats: { armyDefense: 0.912 } },
    { name: "Elder Garb", level: 25, set: 'no-set', icon: 'icons/items/Elder_Garb.webp', stats: { researchSpeed: 0.88, siegeAttack: 0.8 } },
    { name: "Guardian Chestplate", level: 7, set: 'no-set', icon: 'icons/items/Guardian_Chestplate.webp', stats: { constructionSpeed: 0.24, armyHp: 0.16 } },
    { name: "Odysseus", level: 40, set: 'no-set', icon: 'icons/items/Odysseus.webp', stats: { constructionSpeed: 0.832, siegeAttack: 1.2, armyDefense: 0.992 } },
    { name: "Prowler Vest", level: 31, set: 'no-set', icon: 'icons/items/Prowler_Vest.webp', stats: { siegeAttack: 0.96, armyDefense: 0.8 } },
    { name: "Regal Platemail", level: 40, set: 'no-set', icon: 'icons/items/Regal_Platemail.webp', stats: { siegeAttack: 1.2, armyHp: 0.8 } },
    { name: "Summoner Robe", level: 31, set: 'no-set', icon: 'icons/items/Summoner_Robe.webp', stats: { foodProduction: 4.32, siegeAttack: 0.96, armyDefense: 0.8 } },
    { name: "Wyvern Soul", level: 19, set: 'no-set', icon: 'icons/items/Wyvern_Soul.webp', stats: { siegeAttack: 0.608, armyHp: 0.416 } },
    { name: "Ceremonial Toga", level: 13, set: 'no-set', icon: 'icons/items/Ceremonial_Toga.webp', stats: { siegeAttack: 0.48 } },
    { name: "Lightning Guard", level: 45, set: 'noceros', icon: 'icons/items/Lightning_Guard.png', stats: { goldProduction: 8.0, constructionSpeed: 3.2, gatheringSpeed: 3.2 } },
    { name: "Hardened Carapace", level: 55, set: 'queen-bee', icon: 'icons/items/Hardened_Carapace.png', stats: { cavalryAttack: 4.0, rangedAttack: 4.0, armyDefense: 1.5 } },
    { name: "Predator Pauldrons", level: 50, set: 'saberfang', icon: 'icons/items/Predator_Pauldrons.webp', stats: { cavalryAttack: 1.5, cavalryHp: 3.2, armyDefense: 2.4, travelSpeed: 4.0 } },
    { name: "Winter Parka", level: 50, set: 'snow-beast', icon: 'icons/items/Winter_Parka.webp', stats: { infantryAttack: 2.0, cavalryDefense: 4.0, armyHp: 2.5 } },
    { name: "Energy Backpack", level: 45, set: 'steampath', icon: 'icons/items/Energy_Backpack.webp', stats: { craftingSpeed: 1.7, rangedDefense: 0.8, craftingCapacity: 11.0 } },
    { name: "Spooky Coat", level: 45, set: 'cottageroar', icon: 'icons/sets/Spooky_Coat.webp', stats: { infantryAttack: 1.8, infantryDefense: 1.6, infantryHp: 1.3 } },
    { name: "Terror Shield", level: 60, set: 'terrorthorn', icon: 'icons/items/Terror_Shield.webp', stats: { infantryAttack: 5.6, infantryHp: 4.0, armyHp: 2.4, researchSpeed: 1.25 } },
    { name: "Hunting Plate", level: 50, set: 'hunter', icon: 'icons/items/Hunting_Plate.png', stats: { monsterHuntTravelSpeed: 1.6, maxEnergy: 160.0, monsterHuntDmg: 3.2 } },
    { name: "Spirit Mantle", level: 40, set: 'voodoo-shaman', icon: 'icons/items/Spirit_Mantle.png', stats: { mergingSpeed: 1.5, familiarTrainingExp: 4.8 } },
  ],
  [SLOTS.LEGS]: [
    { name: "Blizzard Pants", level: 60, set: 'arctic-flipper', icon: 'icons/items/Blizzard_Pants.webp', stats: { cavalryAttack: 4.8, rangedAttack: 4.8, armyDefense: 1.6, armyHp: 1.9 } },
    { name: "Dragon's Talon", level: 60, set: 'blackwing', icon: 'icons/items/Dragons_Talon.webp', stats: { infantryAttack: 3.2, rangedAttack: 4.8, armyHp: 2.4 } },
    { name: "Champion Boots", level: 60, set: 'champion', icon: 'icons/items/Champion_Boots.png', stats: { rangedAttack: 6.4, armyAttack: 1.5, armyHp: 3.5, travelSpeed: 8.0 } },
    { name: "Champion Greaves", level: 60, set: 'champion', icon: 'icons/items/Champion_Greaves.png', stats: { cavalryAttack: 6.4, armyAttack: 1.5, armyHp: 3.5, travelSpeed: 8.0 } },
    { name: "Champion Stride", level: 60, set: 'champion', icon: 'icons/items/Champion_Stride.png', stats: { infantryAttack: 4.8, armyAttack: 1.5, armyHp: 3.5, travelSpeed: 8.0 } },
    { name: "Stately Tassets", level: 60, set: 'emperor', icon: 'icons/items/Stately_Tassets.webp', fixedGrade: 'Mythic', stats: { armyAttack: 40.0, armyDefense: 25.0, armyHp: 25.0 } },
    { name: "NewItem13", level: 60, set: 'exalted', icon: 'icons/items/NewItem13.webp', fixedGrade: 'Mythic', stats: { armyAttack: 35.0, armyDefense: 20.0, armyHp: 20.0 } },
    { name: "Frostwing Boots", level: 40, set: 'frostwing', icon: 'icons/items/Frostwing_Boots.webp', stats: { cavalryAttack: 0.95, siegeAttack: 0.8, wallDefense: 2.35 } },
    { name: "Gargantuan Belt", level: 60, set: 'gargantua', icon: 'icons/items/Gargantuan_Belt.webp', stats: { cavalryAttack: 6.0, cavalryHp: 4.5, armyDefense: 2.4, stoneProduction: 8.0 } },
    { name: "Beastly Waistguard", level: 50, set: 'gawrilla', icon: 'icons/items/Beastly_Waistguard.webp', stats: { cavalryAttack: 2.55, cavalryHp: 1.9, armyDefense: 1.9 } },
    { name: "Nether Walkers", level: 45, set: 'grim-reaper', icon: 'icons/items/Nether_Walkers.webp', stats: { rangedAttack: 2.4, rangedDefense: 1.5, armyDefense: 2.4 } },
    { name: "Gryphon Walkers", level: 55, set: 'gryphon', icon: 'icons/items/Gryphon_Walkers.png', stats: { foodProduction: 16.0, constructionSpeed: 5.6, researchSpeed: 2.8 } },
    { name: "Craggy Greaves", level: 50, set: 'hardrox', icon: 'icons/items/Craggy_Greaves.png', stats: { trainingSpeed: 1.5, gatheringSpeed: 3.2, oreProduction: 4.0 } },
    { name: "Legs of the Deceiver", level: 55, set: 'hell-drider', icon: 'icons/items/Legs_of_the_Deceiver.webp', stats: { rangedAttack: 0.8, rangedDefense: 2.4, armyAttack: 1.95 } },
    { name: "Stealthy Steps", level: 50, set: 'hootclaw', icon: 'icons/items/Stealthy_Steps.webp', stats: { rangedAttack: 2.55, rangedDefense: 3.2, armyHp: 1.3 } },
    { name: "Kung Fu Wraps", level: 60, set: 'kung-fu-panda', icon: 'icons/items/Kung_Fu_Wraps.webp', fixedGrade: 'Legendary', stats: { cavalryAttack: 5.0, cavalryDefense: 5.0, cavalryHp: 5.0 } },
    { name: "Corrupted Boots", level: 40, set: 'mecha-trojan', icon: 'icons/items/Corrupted_Boots.webp', stats: { infantryAttack: 1.5, siegeAttack: 2.4, infantryDefense: 1.5 } },
    { name: "Amethyst Boots", level: 40, set: 'no-set', icon: 'icons/items/Amethyst_Boots.webp', stats: { constructionSpeed: 0.64, cavalryAttack: 0.72, rangedAttack: 0.72 } },
    { name: "Atlas Ankle Locks", level: 23, set: 'no-set', icon: 'icons/items/Atlas_Ankle_Locks.webp', stats: { rangedAttack: 0.4, armyDefense: 0.96 } },
    { name: "Cobra Sandals", level: 29, set: 'no-set', icon: 'icons/items/Cobra_Sandals.webp', stats: { cavalryAttack: 0.56, rangedAttack: 0.56 } },
    { name: "Durable Boots", level: 40, set: 'no-set', icon: 'icons/items/Durable_Boots.webp', stats: { cavalryAttack: 0.72, rangedAttack: 0.72, armyDefense: 1.6 } },
    { name: "Dwarven Toe Guard", level: 17, set: 'no-set', icon: 'icons/items/Dwarven_Toe_Guard.webp', stats: { goldProduction: 2.56, rangedAttack: 0.32, wallDefense: 0.4 } },
    { name: "Goatskin Boots", level: 11, set: 'no-set', icon: 'icons/items/Goatskin_Boots.webp', stats: { cavalryAttack: 0.24, wallDefense: 0.32 } },
    { name: "Marsh Treadders", level: 3, set: 'no-set', icon: 'icons/items/Marsh_Treadders.webp', stats: { constructionSpeed: 0.16, rangedAttack: 0.16 } },
    { name: "Nomad Boots", level: 29, set: 'no-set', icon: 'icons/items/Nomad_Boots.webp', stats: { cavalryAttack: 0.4, wallDefense: 0.8 } },
    { name: "Seafarer Cleats", level: 35, set: 'no-set', icon: 'icons/items/Seafarer_Cleats.webp', stats: { constructionSpeed: 0.4, cavalryAttack: 0.64 } },
    { name: "Sylph Sandals", level: 35, set: 'no-set', icon: 'icons/items/Sylph_Sandals.webp', stats: { cavalryAttack: 0.4, rangedAttack: 0.64, wallDefense: 0.88 } },
    { name: "Honeycomb Chaps", level: 40, set: 'queen-bee', icon: 'icons/items/Honeycomb_Chaps.webp', stats: { cavalryAttack: 1.8, rangedAttack: 1.8, rangedDefense: 0.8 } },
    { name: "Untamed Boots", level: 55, set: 'saberfang', icon: 'icons/items/Untamed_Boots.webp', stats: { cavalryAttack: 3.2, cavalryDefense: 2.4, armyHp: 2.4, travelSpeed: 4.8 } },
    { name: "Sacred Boots", level: 60, set: 'sacred', icon: 'icons/items/Sacred_Boots.webp', fixedGrade: 'Legendary', stats: { gatheringSpeed: 10.0 } },
    { name: "Sacred Greaves", level: 60, set: 'sacred', icon: 'icons/items/Sacred_Greaves.webp', fixedGrade: 'Legendary', stats: { researchSpeed: 10.0, travelSpeed: 5.0, goldProduction: 10.0 } },
    { name: "Desert Trousers", level: 45, set: 'serpent-gladiator', icon: 'icons/items/Desert_Trousers.webp', stats: { infantryAttack: 1.6, rangedAttack: 1.6, rangedDefense: 1.1, infantryHp: 0.5 } },
    { name: "Winter Stompers", level: 45, set: 'snow-beast', icon: 'icons/items/Winter_Stompers.webp', stats: { cavalryAttack: 1.15, rangedDefense: 4.0, armyDefense: 2.05 } },
    { name: "Storm Tasset", level: 60, set: 'tidal-titan', icon: 'icons/items/Storm_Tasset.webp', stats: { infantryAttack: 4.8, cavalryAttack: 4.8, armyDefense: 3.2, armyHp: 1.5 } },
    { name: "Mechanical Boots", level: 50, set: 'steampath', icon: 'icons/sets/Mechanical_Boots.webp', stats: { craftingSpeed: 1.7, craftingCapacity: 22.0, oreProduction: 2.4 } },
    { name: "Steps of Reckoning", level: 50, set: 'cottageroar', icon: null, stats: { infantryAttack: 2.55, infantryDefense: 1.9, infantryHp: 1.3 } },
    { name: "Hunting Greaves", level: 55, set: 'hunter', icon: 'icons/items/Hunting_Greaves.png', stats: { monsterHuntTravelSpeed: 4.5, maxEnergy: 320.0, monsterHuntDmg: 0.8 } },
    { name: "Ancestral Kilt", level: 40, set: 'voodoo-shaman', icon: 'icons/items/Ancestral_Kilt.png', stats: { mergingSpeed: 3.2, familiarTrainingExp: 1.5 } },
  ],
};

const ACCESSORY_ITEMS = [
  { name: "Polar Ring", level: 60, set: 'arctic-flipper', icon: 'icons/items/Polar_Ring.webp', stats: { cavalryAttack: 4.0, rangedAttack: 4.0, cavalryHp: 2.4, rangedHp: 2.4 } },
  { name: "Dragon's Iris", level: 55, set: 'blackwing', icon: 'icons/items/Dragons_Iris.png', stats: { cavalryAttack: 1.5, rangedAttack: 1.5, armyHp: 1.5 } },
  { name: "Ambrosial Cup", level: 60, set: 'bon-appeti', icon: 'icons/items/Ambrosial_Cup.png', stats: { infantryAttack: 4.0, rangedAttack: 4.0, infantryHp: 2.4, rangedHp: 2.4 } },
  { name: "Champion Blessing", level: 60, set: 'champion', icon: 'icons/items/Champion_Blessing.png', stats: { infantryAttack: 2.4, rangedAttack: 2.4, armyAttack: 1.5, armyHp: 4.0 } },
  { name: "Champion Faith", level: 60, set: 'champion', icon: 'icons/items/Champion_Faith.png', stats: { infantryAttack: 2.4, cavalryAttack: 2.4, armyAttack: 1.5, armyHp: 4.0 } },
  { name: "Champion Valor", level: 60, set: 'champion', icon: 'icons/items/Champion_Valor.png', stats: { cavalryAttack: 2.4, rangedAttack: 2.4, armyAttack: 1.5, armyHp: 4.0 } },
  { name: "Sovereign Signet", level: 60, set: 'emperor', icon: 'icons/items/Sovereign_Signet.webp', fixedGrade: 'Mythic', stats: { armyAttack: 30.0, armyDefense: 20.0, armyHp: 20.0 } },
  { name: "Frostwing's Breath", level: 55, set: 'frostwing', icon: 'icons/items/Frostwings_Breath.png', stats: { infantryAttack: 1.25, cavalryAttack: 1.25, goldProduction: 8.0 } },
  { name: "Fear Drum", level: 50, set: 'gargantua', icon: 'icons/items/Fear_Drum.png', stats: { cavalryAttack: 2.55, siegeAttack: 1.5, cavalryHp: 0.85, goldProduction: 5.6 } },
  { name: "Rowdy Resolve", level: 60, set: 'gawrilla', icon: 'icons/items/Rowdy_Resolve.webp', stats: { cavalryAttack: 4.0, cavalryHp: 1.6, cavalryDefense: 1.2 } },
  { name: "Burning Scroll", level: 55, set: 'hell-drider', icon: 'icons/items/Burning_Scroll.png', stats: { armyAttack: 1.45, armyHp: 1.45, timberProduction: 5.5 } },
  { name: "Wyrm Seal", level: 55, set: 'jade-wyrm', icon: 'icons/items/Wyrm_Seal.webp', stats: { rangedAttack: 2.55, siegeAttack: 2.4, armyHp: 1.2, stoneProduction: 5.6 } },
  { name: "Secret Totem", level: 45, set: 'mecha-trojan', icon: 'icons/items/Secret_Totem.png', stats: { infantryAttack: 1.15, siegeAttack: 2.4, infantryHp: 2.4, armyDefense: 1.15 } },
  { name: "Blight Ring", level: 60, set: 'mega-maggot', icon: 'icons/items/Blight_Ring.webp', stats: { rangedAttack: 2.2, armyDefense: 2.4, armyHp: 2.4, wallDefense: 4.0 } },
  { name: "Book of the Dead", level: 60, set: 'necrosis', icon: 'icons/items/Book_of_the_Dead.webp', stats: { infantryAttack: 4.0, cavalryAttack: 4.0, cavalryDefense: 3.2, infantryHp: 2.4 } },
  { name: "Collab Item06", level: 60, set: 'night-fury', icon: 'icons/items/Collab_Item06.webp', fixedGrade: 'Legendary', stats: { constructionSpeed: 5.0, researchSpeed: 3.0 } },
  { name: "Amber Ring", level: 21, set: 'no-set', icon: 'icons/items/Amber_Ring.webp', stats: { constructionSpeed: 2.0, wallDefense: 0.16 } },
  { name: "Ancient Hourglass", level: 27, set: 'no-set', icon: 'icons/items/Ancient_Hourglass.png', stats: { researchSpeed: 1.52, goldProduction: 3.6 } },
  { name: "Crystal Tear", level: 27, set: 'no-set', icon: 'icons/items/Crystal_Tear.png', stats: { goldProduction: 3.6, cavalryAttack: 0.64, siegeAttack: 1.04 } },
  { name: "Lost Island's Relic", level: 40, set: 'no-set', icon: 'icons/items/Lost_Islands_Relic.png', stats: { infantryAttack: 0.96, rangedAttack: 0.96, armyHp: 0.4 } },
  { name: "Lost Pocketwatch", level: 33, set: 'no-set', icon: 'icons/items/Lost_Pocketwatch.png', stats: { constructionSpeed: 2.88, researchSpeed: 1.84, trapAttack: 0.88 } },
  { name: "Lunar Flute", level: 40, set: 'no-set', icon: 'icons/items/Lunar_Flute.webp', stats: { researchSpeed: 4.16, foodProduction: 6.08, armyHp: 0.4 } },
  { name: "Mystic Box", level: 45, set: 'no-set', icon: 'icons/items/Mystic_Box.webp', stats: { infantryAttack: 0.96, mergingSpeed: 4.0, familiarTrainingExp: 4.0 } },
  { name: "Neptune's Necklace", level: 27, set: 'no-set', icon: 'icons/items/Neptunes_Necklace.png', stats: { constructionSpeed: 2.4, infantryAttack: 0.64, wallDefense: 0.24 } },
  { name: "Pirate's Eye Patch", level: 9, set: 'no-set', icon: 'icons/items/Pirates_Eye_Patch.png', stats: { constructionSpeed: 1.28, researchSpeed: 0.8 } },
  { name: "Prehistoric Horn", level: 15, set: 'no-set', icon: 'icons/items/Prehistoric_Horn.webp', stats: { goldProduction: 2.08, armyHp: 0.16 } },
  { name: "Hortensia Diamond", level: 33, set: 'no-set', icon: 'icons/sets/Hortensia_Diamond.webp', stats: { foodProduction: 5.52, wallDefense: 0.24 } },
  { name: "Power Vials", level: 60, set: 'steampath', icon: 'icons/sets/Power_Vials.webp', stats: { craftingSpeed: 1.7, craftingCapacity: 34.0, stoneProduction: 2.4 } },
  { name: "Sentinel's Circlet", level: 40, set: 'no-set', icon: 'icons/items/Sentinels_Circlet.png', stats: { constructionSpeed: 4.0, cavalryAttack: 0.64, siegeAttack: 1.44 } },
  { name: "Star Dust", level: 27, set: 'no-set', icon: 'icons/items/Star_Dust.webp', stats: { foodProduction: 4.32, rangedAttack: 0.64, armyHp: 0.32 } },
  { name: "Ivory Choker", level: 40, set: 'saberfang', icon: 'icons/items/Ivory_Choker.png', stats: { cavalryAttack: 1.2, trapAttack: 2.4, trapDefense: 2.4, travelSpeed: 1.2 } },
  { name: "Sagittarius Wings", level: 60, set: 'sagittarius', icon: 'icons/items/Sagittarius_Wings.webp', fixedGrade: 'Legendary', stats: { constructionSpeed: 5.0, researchSpeed: 5.0 } },
  { name: "Coiled Armband", level: 50, set: 'serpent-gladiator', icon: 'icons/items/Coiled_Armband.webp', stats: { infantryAttack: 2.1, rangedAttack: 2.1, infantryDefense: 1.6, rangedHp: 1.3 } },
  { name: "Terror Vial", level: 50, set: 'terrorthorn', icon: 'icons/items/Terror_Vial.png', stats: { infantryAttack: 2.55, infantryHp: 0.8, armyDefense: 1.2, oreProduction: 5.6 } },
  { name: "Aqua Anemone", level: 40, set: 'tidal-titan', icon: 'icons/items/Aqua_Anemone.webp', stats: { infantryAttack: 1.2, cavalryAttack: 1.2 } },
  { name: "Hunting Horn", level: 45, set: 'hunter', icon: 'icons/items/Hunting_Horn.png', stats: { monsterHuntTravelSpeed: 3.2, maxEnergy: 80.0, monsterHuntDmg: 0.8 } },
];

ITEMS[SLOTS.ACCESSORY_1] = ACCESSORY_ITEMS;
ITEMS[SLOTS.ACCESSORY_2] = ACCESSORY_ITEMS;
ITEMS[SLOTS.ACCESSORY_3] = ACCESSORY_ITEMS;

// Получить локализованное название стата.
// Префикс eff_ означает «эффективный» (база войска + соответствующий армейский бонус).
function statLabel(key) {
  if (key && key.indexOf('eff_') === 0) return t('stat.' + key.slice(4));
  return t('stat.' + key);
}

// Локализованное имя предмета. Если перевода нет — возвращаем оригинал.
function itemLabel(name) {
  const dict = LOCALES[getLocale()];
  const tr = dict && dict['item.' + name];
  return tr || name;
}

// Локализованное имя сета. Если перевода нет — возвращаем оригинал.
function setLabel(id, fallback) {
  const dict = LOCALES[getLocale()];
  const tr = dict && dict['set.' + id];
  return tr || fallback || id;
}
const JEWEL_GRADE_ORDER = ['Common', 'Uncommon', 'Rare', 'Epic', 'Legendary'];

const JEWEL_CATEGORIES = [
  { id: 'standard',      name: 'Standard' },
  { id: 'monster',       name: 'Monster' },
  { id: 'bundle',        name: 'Bundle' },
  { id: 'turf',          name: 'Turf' },
  { id: 'assault',       name: 'Assault' },
  { id: 'battle-royal',  name: 'Battle Royal' },
  { id: 'feudal-war',    name: 'Feudal War' },
  { id: 'dragon-arena',  name: 'Dragon Arena' },
];

const JEWELS = [
  { id: 'infantry-atk', name: "Infantry ATK Jewel", category: 'standard', icon: 'icons/jewels/Infantry_ATK_Jewel.webp', stat: 'infantryAttack', values: [1.0, 3.0, 6.0, 12.0, 20.0] },
  { id: 'ranged-atk', name: "Ranged ATK Jewel", category: 'standard', icon: 'icons/jewels/Ranged_ATK_Jewel.webp', stat: 'rangedAttack', values: [1.0, 3.0, 6.0, 12.0, 20.0] },
  { id: 'cavalry-atk', name: "Cavalry ATK Jewel", category: 'standard', icon: 'icons/jewels/Cavalry_ATK_Jewel.webp', stat: 'cavalryAttack', values: [1.0, 3.0, 6.0, 12.0, 20.0] },
  { id: 'engine-atk', name: "Engine ATK Jewel", category: 'standard', icon: 'icons/jewels/Engine_ATK_Jewel.webp', stat: 'siegeAttack', values: [1.0, 3.0, 6.0, 12.0, 20.0] },
  { id: 'trap-atk', name: "Trap ATK Jewel", category: 'standard', icon: 'icons/jewels/Trap_ATK_Jewel.webp', stat: 'trapAttack', values: [1.0, 3.0, 6.0, 12.0, 20.0] },
  { id: 'infantry-def', name: "Infantry DEF Jewel", category: 'standard', icon: 'icons/jewels/Infantry_DEF_Jewel.webp', stat: 'infantryDefense', values: [1.0, 3.0, 6.0, 12.0, 20.0] },
  { id: 'ranged-def', name: "Ranged DEF Jewel", category: 'standard', icon: 'icons/jewels/Ranged_DEF_Jewel.webp', stat: 'rangedDefense', values: [1.0, 3.0, 6.0, 12.0, 20.0] },
  { id: 'cavalry-def', name: "Cavalry DEF Jewel", category: 'standard', icon: 'icons/jewels/Cavalry_DEF_Jewel.webp', stat: 'cavalryDefense', values: [1.0, 3.0, 6.0, 12.0, 20.0] },
  { id: 'trap-def', name: "Trap DEF Jewel", category: 'standard', icon: 'icons/jewels/Trap_DEF_Jewel.webp', stat: 'trapDefense', values: [1.0, 3.0, 6.0, 12.0, 20.0] },
  { id: 'wall-def', name: "Wall DEF Jewel", category: 'standard', icon: 'icons/jewels/Wall_DEF_Jewel.webp', stat: 'wallDefense', values: [1.0, 3.0, 6.0, 12.0, 20.0] },
  { id: 'gargantua', name: "Gargantua Jewel", category: 'monster', icon: 'icons/jewels/Gargantua_Jewel.webp', stat: 'cavalryAttack', values: [0.4, 0.8, 2.0, 5.0, 10.0] },
  { id: 'wyrm', name: "Wyrm Jewel", category: 'monster', icon: 'icons/jewels/Wyrm_Jewel.webp', stat: 'rangedAttack', values: [0.4, 0.8, 2.0, 5.0, 10.0] },
  { id: 'terror', name: "Terror Jewel", category: 'monster', icon: 'icons/jewels/Terror_Jewel.webp', stat: 'infantryAttack', values: [0.4, 0.8, 2.0, 5.0, 10.0] },
  { id: 'gryphon', name: "Gryphon Jewel", category: 'monster', icon: 'icons/jewels/Gryphon_Jewel.webp', stat: 'trapAttack', values: [0.4, 0.8, 2.0, 5.0, 10.0] },
  { id: 'saber', name: "Saber Jewel", category: 'monster', icon: 'icons/jewels/Saber_Jewel.webp', stat: 'cavalryHp', values: [0.6, 1.2, 3.0, 7.5, 15.0] },
  { id: 'grim', name: "Grim Jewel", category: 'monster', icon: 'icons/jewels/Grim_Jewel.webp', stat: 'rangedHp', values: [0.6, 1.2, 3.0, 7.5, 15.0] },
  { id: 'trojan', name: "Trojan Jewel", category: 'monster', icon: 'icons/jewels/Trojan_Jewel.webp', stat: 'infantryHp', values: [0.6, 1.2, 3.0, 7.5, 15.0] },
  { id: 'noceros', name: "Noceros Jewel", category: 'monster', icon: 'icons/jewels/Noceros_Jewel.webp', stat: 'foodProduction', values: [1.2, 2.4, 6.0, 15.0, 30.0] },
  { id: 'swift-hunter', name: "Swift Hunter Jewel", category: 'bundle', icon: 'icons/jewels/Swift_Hunter_Jewel.webp', stat: 'maxEnergy', values: [40.0, 80.0, 200.0, 500.0, 1000.0] },
  { id: 'steampath', name: "Steampath Jewel", category: 'bundle', icon: 'icons/jewels/Steampath_Jewel.webp', stat: 'craftingSpeed', values: [0.2, 0.4, 1.0, 2.5, 5.0] },
  { id: 'champion', name: "Champion Jewel", category: 'bundle', icon: 'icons/jewels/Champion_Jewel.webp', stat: 'travelSpeed', values: [0.8, 1.6, 4.0, 10.0, 20.0] },
  { id: 'research', name: "Research Jewel", category: 'turf', icon: 'icons/jewels/Research_Jewel.webp', stat: 'researchSpeed', values: [0.2, 0.4, 1.0, 2.5, 5.0] },
  { id: 'construction', name: "Construction Jewel", category: 'turf', icon: 'icons/jewels/Construction_Jewel.webp', stat: 'constructionSpeed', values: [0.2, 0.4, 1.0, 2.5, 5.0] },
  { id: 'army-assault', name: "Army Assault Jewel", category: 'assault', icon: 'icons/jewels/Army_Assault_Jewel.webp', stat: 'armyAttack', values: [0.4, 0.8, 2.0, 5.0, 10.0] },
  { id: 'ic-assault', name: "IC Assault Jewel", category: 'assault', icon: 'icons/jewels/IC_Assault_Jewel.webp', stat: 'infantryAttack', values: [0.4, 0.8, 2.0, 5.0, 10.0] },
  { id: 'cr-assault', name: "CR Assault Jewel", category: 'assault', icon: 'icons/jewels/CR_Assault_Jewel.webp', stat: 'cavalryAttack', values: [0.4, 0.8, 2.0, 5.0, 10.0] },
  { id: 'ri-assault', name: "RI Assault Jewel", category: 'assault', icon: 'icons/jewels/RI_Assault_Jewel.webp', stat: 'rangedAttack', values: [0.4, 0.8, 2.0, 5.0, 10.0] },
  { id: 'royal-cavalry', name: "Royal Cavalry Jewel", category: 'battle-royal', icon: 'icons/jewels/Royal_Cavalry_Jewel.webp', stat: 'cavalryAttack', values: [0.4, 0.8, 2.0, 5.0, 10.0] },
  { id: 'royal-ranged', name: "Royal Ranged Jewel", category: 'battle-royal', icon: 'icons/jewels/Royal_Ranged_Jewel.webp', stat: 'rangedAttack', values: [0.4, 0.8, 2.0, 5.0, 10.0] },
  { id: 'royal-infantry', name: "Royal Infantry Jewel", category: 'battle-royal', icon: 'icons/jewels/Royal_Infantry_Jewel.webp', stat: 'infantryAttack', values: [0.4, 0.8, 2.0, 5.0, 10.0] },
  { id: 'eagle', name: "Eagle Jewel", category: 'feudal-war', icon: 'icons/jewels/Eagle_Jewel.webp', stat: 'cavalryAttack', values: [0.6, 1.2, 3.0, 7.5, 15.0] },
  { id: 'falcon', name: "Falcon Jewel", category: 'feudal-war', icon: 'icons/jewels/Falcon_Jewel.webp', stat: 'rangedAttack', values: [0.6, 1.2, 3.0, 7.5, 15.0] },
  { id: 'hawk', name: "Hawk Jewel", category: 'feudal-war', icon: 'icons/jewels/Hawk_Jewel.webp', stat: 'infantryAttack', values: [0.6, 1.2, 3.0, 7.5, 15.0] },
  { id: 'dragon-infantry', name: "Dragon Infantry Jewel", category: 'dragon-arena', icon: 'icons/jewels/Dragon_Infantry_Jewel.webp', stat: 'infantryAttack', values: [0.6, 1.2, 3.0, 7.5, 15.0] },
  { id: 'dragon-ranged', name: "Dragon Ranged Jewel", category: 'dragon-arena', icon: 'icons/jewels/Dragon_Ranged_Jewel.webp', stat: 'rangedAttack', values: [0.6, 1.2, 3.0, 7.5, 15.0] },
  { id: 'dragon-cavalry', name: "Dragon Cavalry Jewel", category: 'dragon-arena', icon: 'icons/jewels/Dragon_Cavalry_Jewel.webp', stat: 'cavalryAttack', values: [0.6, 1.2, 3.0, 7.5, 15.0] },
];